# UAS Machine Learning Semester Ganjil 2023/2024

# Nama: Daffa Asyqar Ahmad Khalisheka
# NIM: 1103200034
# Kelas: TK-44-G4

# 00. PyTorch Fundamentals

## What is PyTorch?

[PyTorch](https://pytorch.org/) is an open source machine learning and deep learning framework.

## What can PyTorch be used for?

PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.

## Who uses PyTorch?

Many of the worlds largest technology companies such as [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/), Tesla and Microsoft as well as artificial intelligence research companies such as [OpenAI use PyTorch](https://openai.com/blog/openai-pytorch/) to power research and bring machine learning to their products.

![pytorch being used across industry and research](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png)

For example, Andrej Karpathy (head of AI at Tesla) has given several talks ([PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE), [Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M?t=2904)) about how Tesla use PyTorch to power their self-driving computer vision models.

PyTorch is also used in other industries such as agriculture to [power computer vision on tractors](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1).

## Why use PyTorch?

Machine learning researchers love using PyTorch. And as of February 2022, PyTorch is the [most used deep learning framework on Papers With Code](https://paperswithcode.com/trends), a website for tracking machine learning research papers and the code repositories attached with them.

PyTorch also helps take care of many things such as GPU acceleration (making your code run faster) behind the scenes.

So you can focus on manipulating data and writing algorithms and PyTorch will make sure it runs fast.

And if companies such as Tesla and Meta (Facebook) use it to build models they deploy to power hundreds of applications, drive thousands of cars and deliver content to billions of people, it's clearly capable on the development front too.

## What we're going to cover in this module

This course is broken down into different sections (notebooks).

Each notebook covers important ideas and concepts within PyTorch.

Subsequent notebooks build upon knowledge from the previous one (numbering starts at 00, 01, 02 and goes to whatever it ends up going to).

This notebook deals with the basic building block of machine learning and deep learning, the tensor.

Specifically, we're going to cover:

| **Topic** | **Contents** |
| ----- | ----- |
| **Introduction to tensors** | Tensors are the basic building block of all of machine learning and deep learning. |
| **Creating tensors** | Tensors can represent almost any kind of data (images, words, tables of numbers). |
| **Getting information from tensors** | If you can put information into a tensor, you'll want to get it out too. |
| **Manipulating tensors** | Machine learning algorithms (like neural networks) involve manipulating tensors in many different ways such as adding, multiplying, combining. |
| **Dealing with tensor shapes** | One of the most common issues in machine learning is dealing with shape mismatches (trying to mixed wrong shaped tensors with other tensors). |
| **Indexing on tensors** | If you've indexed on a Python list or NumPy array, it's very similar with tensors, except they can have far more dimensions. |
| **Mixing PyTorch tensors and NumPy** | PyTorch plays with tensors ([`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)), NumPy likes arrays ([`np.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)) sometimes you'll want to mix and match these. |
| **Reproducibility** | Machine learning is very experimental and since it uses a lot of *randomness* to work, sometimes you'll want that *randomness* to not be so random. |
| **Running tensors on GPU** | GPUs (Graphics Processing Units) make your code faster, PyTorch makes it easy to run your code on GPUs. |

## Where can you get help?

All of the materials for this course [live on GitHub](https://github.com/mrdbourke/pytorch-deep-learning).

And if you run into trouble, you can ask a question on the [Discussions page](https://github.com/mrdbourke/pytorch-deep-learning/discussions) there too.

There's also the [PyTorch developer forums](https://discuss.pytorch.org/), a very helpful place for all things PyTorch.

## Importing PyTorch

> **Note:** Before running any of the code in this notebook, you should have gone through the [PyTorch setup steps](https://pytorch.org/get-started/locally/).
>
> However, **if you're running on Google Colab**, everything should work (Google Colab comes with PyTorch and other libraries installed).

Let's start by importing PyTorch and checking the version we're using.

Kode tersebut menggunakan Python dan PyTorch untuk menampilkan versi PyTorch yang terinstall. Mari kita jelaskan langkah-langkahnya:

1. `import torch`: Ini mengimpor modul PyTorch ke dalam program Python. Dengan menggunakan pernyataan `import`, kita dapat menggunakan berbagai fungsi dan fitur yang disediakan oleh PyTorch.

2. `torch.__version__`: Ini adalah pernyataan yang digunakan untuk mendapatkan versi PyTorch yang terinstall di sistem. Pada bagian ini, kita mengakses atribut `__version__` dari objek `torch`, yang berisi informasi tentang versi PyTorch.

Jadi, keseluruhan kode berfungsi untuk mengimpor PyTorch dan menampilkan versi PyTorch yang terinstall di lingkungan Python saat itu. Jika Anda menjalankan kode ini, itu akan mencetak versi PyTorch ke konsol atau output yang digunakan dalam lingkungan eksekusi Python Anda.

In [ ]:
import torch
torch.__version__

'1.13.1+cu116'

Versi PyTorch yang ditampilkan dalam output, yaitu '1.13.1+cu116', menyediakan beberapa informasi yang dapat diartikan sebagai berikut:

1. **1.13.1**: Ini adalah nomor versi utama dari PyTorch. Dalam hal ini, versi utama adalah 1.

2. **cu116**: Bagian 'cu116' menunjukkan bahwa PyTorch dikompilasi untuk menggunakan CUDA versi 11.6. CUDA adalah platform komputasi paralel dari NVIDIA yang digunakan untuk mempercepat perhitungan pada GPU (Graphics Processing Unit).

Jadi, secara keseluruhan, versi PyTorch yang terinstall adalah versi 1.13.1 yang dikompilasi untuk menggunakan CUDA versi 11.6. Informasi ini dapat berguna saat memastikan bahwa PyTorch dapat berinteraksi dengan perangkat keras GPU dan memanfaatkan fitur-fitur yang diberikan oleh CUDA untuk percepatan perhitungan.

Wonderful, it looks like we've got PyTorch 1.10.0+.

This means if you're going through these materials, you'll see most compatability with PyTorch 1.10.0+, however if your version number is far higher than that, you might notice some inconsistencies.

And if you do have any issues, please post on the course [GitHub Discussions page](https://github.com/mrdbourke/pytorch-deep-learning/discussions).

## Introduction to tensors

Now we've got PyTorch imported, it's time to learn about tensors.

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, height, width]`, as in the image has `3` colour channels (red, green, blue), a height of `224` pixels and a width of `224` pixels.

![example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

In tensor-speak (the language used to describe tensors), the tensor would have three dimensions, one for `colour_channels`, `height` and `width`.

But we're getting ahead of ourselves.

Let's learn more about tensors by coding them.


### Creating tensors

PyTorch loves tensors. So much so there's a whole documentation page dedicated to the [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) class.

Your first piece of homework is to [read through the documentation on `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) for 10-minutes. But you can get to that later.

Let's code.

The first thing we're going to create is a **scalar**.

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

> **Note:** That's a trend for this course. We'll focus on writing specific code. But often I'll set exercises which involve reading and getting familiar with the PyTorch documentation. Because after all, once you're finished this course, you'll no doubt want to learn more. And the documentation is somewhere you'll be finding yourself quite often.

Kode tersebut membuat sebuah tensor PyTorch dengan dimensi skalar. Mari kita bahas setiap bagian dari kodenya:

1. **`scalar = torch.tensor(7)`**: Ini adalah pernyataan yang membuat tensor PyTorch. `torch.tensor(7)` membuat tensor dengan nilai skalar 7. Dalam konteks PyTorch, tensor adalah struktur data utama yang digunakan untuk menghitung operasi numerik.

2. **`scalar`**: Ini adalah nama variabel yang digunakan untuk menyimpan tensor yang telah dibuat. Variabel ini dapat digunakan nanti dalam program untuk merujuk ke tensor tersebut.

3. **`scalar` diikuti oleh baris baru atau dijalankan dalam prompt Python tanpa variabel tambahan**: Ini mencetak nilai tensor ke konsol atau output di lingkungan eksekusi Python. Jadi, jika Anda mengeksekusi kode ini, Anda akan melihat output yang menunjukkan nilai tensor skalar, yaitu 7.

Hasil outputnya akan tampak seperti:

```plaintext
tensor(7)
```

Dengan demikian, kode ini menciptakan tensor skalar dengan nilai 7 dan kemudian menampilkan tensor tersebut.

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

Hasil output `tensor(7)` adalah representasi tensor PyTorch dengan nilai skalar 7. Mari kita jabarkan elemen-elemen dalam output tersebut:

- **`tensor`**: Ini menunjukkan bahwa yang ditampilkan adalah sebuah tensor, yaitu struktur data PyTorch yang dapat menyimpan nilai numerik dalam berbagai dimensi.

- **`(7)`**: Ini menunjukkan nilai di dalam tensor. Dalam kasus ini, nilainya adalah 7. Ini adalah nilai skalar, karena tensor tersebut hanya memiliki satu elemen (tidak memiliki dimensi tambahan seperti vektor atau matriks).

Jadi, secara keseluruhan, output tersebut memberikan informasi bahwa kita memiliki sebuah tensor dengan nilai skalar 7. Dalam PyTorch, hasil ini adalah representasi default dari tensor ketika kita mencetaknya.

See how the above printed out `tensor(7)`?

That means although `scalar` is a single number, it's of type `torch.Tensor`.

We can check the dimensions of a tensor using the `ndim` attribute.

`scalar.ndim` adalah kode yang mencoba untuk mengakses atribut `ndim` dari tensor `scalar`. Atribut `ndim` mengembalikan jumlah dimensi dari tensor. Namun, dalam konteks ini, kita harus menyadari bahwa tensor `scalar` sebelumnya didefinisikan sebagai tensor skalar, yang artinya hanya memiliki satu elemen dan tidak memiliki dimensi tambahan seperti vektor atau matriks.

Ketika kita mencoba mengakses `ndim` pada tensor skalar, yang seharusnya tidak memiliki dimensi tambahan, hal itu mungkin menghasilkan pesan kesalahan atau output yang tidak relevan. PyTorch mungkin mengembalikan nilai 0 atau tidak mengembalikan apa-apa, karena tensor skalar tidak memiliki dimensi tambahan.

Oleh karena itu, dalam konteks ini, `scalar.ndim` mungkin tidak memberikan informasi yang bermakna karena tensor skalar secara intrinsik tidak memiliki dimensi tambahan untuk dihitung.

In [ ]:
scalar.ndim

0

What if we wanted to retrieve the number from the tensor?

As in, turn it from `torch.Tensor` to a Python integer?

To do we can use the `item()` method.

Kode ini bertujuan untuk mendapatkan nilai Python dari dalam tensor, khususnya untuk tensor yang hanya memiliki satu elemen. Mari kita bahas penjelasan dari kodenya:

1. **`scalar.item()`**: Ini adalah metode yang digunakan untuk mendapatkan nilai Python dari dalam tensor. Metode ini bekerja dengan baik pada tensor yang hanya memiliki satu elemen, seperti tensor skalar.

2. **`scalar`**: Merujuk ke tensor yang telah didefinisikan sebelumnya.

3. **`.item()`**: Metode ini digunakan untuk mengakses nilai dalam tensor sebagai nilai Python biasa. Ini hanya berfungsi dengan tensor yang memiliki tepat satu elemen, seperti tensor skalar.

Jadi, jika kita memiliki tensor yang hanya berisi satu elemen, kita dapat menggunakan `.item()` untuk mendapatkan nilai Python dari dalamnya. Ini berguna karena tensor di PyTorch sebenarnya adalah objek yang kompleks, dan dalam beberapa kasus, kita hanya ingin mendapatkan nilai mentahnya sebagai tipe data Python biasa. Namun, perlu diingat bahwa metode ini hanya bekerja pada tensor dengan satu elemen. Jika tensor memiliki lebih dari satu elemen, penggunaan `.item()` dapat menghasilkan kesalahan.

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

Okay, now let's see a **vector**.

A vector is a single dimension tensor but can contain many numbers.

As in, you could have a vector `[3, 2]` to describe `[bedrooms, bathrooms]` in your house. Or you could have `[3, 2, 2]` to describe `[bedrooms, bathrooms, car_parks]` in your house.

The important trend here is that a vector is flexible in what it can represent (the same with tensors).

Kode ini menciptakan tensor vektor dalam PyTorch dengan nilai [7, 7]. Saya akan memberikan penjelasan untuk setiap baris kode dan menunjukkan hasilnya jika dijalankan di Google Colab:

```python
# Baris 1: Import PyTorch
import torch
```

Pertama, kita mengimpor modul PyTorch agar dapat menggunakan fungsionalitasnya.

```python
# Baris 2: Membuat tensor vektor
vector = torch.tensor([7, 7])
```

Selanjutnya, kita membuat tensor vektor menggunakan `torch.tensor` dan memberikan nilai [7, 7] sebagai argumen. Ini menciptakan tensor vektor dengan dua elemen, yaitu 7 dan 7.

```python
# Baris 3: Menampilkan tensor vektor
vector
```

Terakhir, kita hanya menulis variabel `vector` di baris terakhir untuk menampilkan nilai tensor vektor tersebut di output Colab.

Jika Anda menjalankan ketiga baris ini secara bersamaan di Google Colab, hasilnya akan menjadi:

```
tensor([7, 7])
```

Ini adalah representasi tensor vektor PyTorch dengan dua elemen, yaitu 7 dan 7.

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Hasil output `tensor([7, 7])` menunjukkan bahwa kita memiliki tensor vektor dalam PyTorch dengan dua elemen, yaitu 7 dan 7. Mari kita jabarkan elemen-elemen dalam output tersebut:

- **`tensor`**: Ini menunjukkan bahwa yang ditampilkan adalah sebuah tensor, yaitu struktur data PyTorch yang dapat menyimpan nilai numerik dalam berbagai dimensi.

- **`[7, 7]`**: Ini adalah nilai-nilai di dalam tensor. Dalam kasus ini, kita memiliki vektor dengan dua elemen, yaitu 7 dan 7. Elemen-elemen ini diurutkan dalam tanda kurung siku sebagai representasi dari tensor vektor.

Jadi, secara keseluruhan, output tersebut memberikan informasi bahwa kita memiliki sebuah tensor vektor dengan dua elemen, yaitu 7 dan 7. Dalam PyTorch, ini adalah cara umum untuk menyajikan vektor atau matriks dalam bentuk tensor.

Wonderful, `vector` now contains two 7's, my favourite number.

How many dimensions do you think it'll have?

Kode tersebut mencoba untuk mengakses atribut `ndim` dari tensor `vector`. Namun, perlu diperhatikan bahwa PyTorch tensor tidak memiliki atribut `ndim`. Sebaliknya, kita dapat menggunakan metode `dim()` untuk mendapatkan jumlah dimensi dari tensor.

Sebagai contoh, kita dapat mengganti kode tersebut menjadi:

```python
vector.dim()
```

Jika kita jalankan kode ini pada tensor `vector` yang telah dibuat sebelumnya (tensor vektor dengan nilai [7, 7]), kita akan mendapatkan output sebagai berikut:

```plaintext
1
```

Output ini menunjukkan bahwa tensor `vector` memiliki satu dimensi, yang sesuai dengan sifat vektor yang hanya memiliki satu dimensi. Jadi, `vector.dim()` memberikan informasi tentang jumlah dimensi dari tensor vektor tersebut.

In [ ]:
# Check the number of dimensions of vector
vector.ndim

1

Hmm, that's strange, `vector` contains two numbers but only has a single dimension.

I'll let you in on a trick.

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside (`[`) and you only need to count one side.

How many square brackets does `vector` have?

Another important concept for tensors is their `shape` attribute. The shape tells you how the elements inside them are arranged.

Let's check out the shape of `vector`.

Kode tersebut mencoba untuk mengakses atribut `shape` dari tensor `vector`. Atribut `shape` pada tensor PyTorch memberikan informasi tentang ukuran atau dimensi dari tensor. Mari kita jelaskan kodenya:

```python
vector.shape
```

Jika kita menjalankan kode ini pada tensor `vector` yang telah dibuat sebelumnya (tensor vektor dengan nilai [7, 7]), kita akan mendapatkan output sebagai berikut:

```plaintext
torch.Size([2])
```

Output ini menunjukkan bahwa tensor `vector` memiliki ukuran atau shape `[2]`. Dalam konteks tensor vektor, ini mengindikasikan bahwa vektor tersebut memiliki panjang (length) 2, yang sesuai dengan jumlah elemen di dalamnya.

Jadi, `vector.shape` memberikan informasi tentang bentuk atau ukuran tensor vektor tersebut. Dalam hal ini, vektor memiliki satu dimensi dengan panjang 2.

In [ ]:
# Check shape of vector
vector.shape

torch.Size([2])

The above returns `torch.Size([2])` which means our vector has a shape of `[2]`. This is because of the two elements we placed inside the square brackets (`[7, 7]`).

Let's now see a **matrix**.

Kode tersebut membuat sebuah tensor matriks dalam PyTorch dengan nilai:

\[
\begin{bmatrix}
7 & 8 \\
9 & 10 \\
\end{bmatrix}
\]

Penjelasan untuk setiap baris kode:

```python
# Membuat tensor matriks
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
```

Dalam baris ini, kita menggunakan fungsi `torch.tensor()` untuk membuat tensor matriks. Matriks tersebut memiliki dua baris dan dua kolom, dengan nilai-nilai yang ditentukan di dalam tanda kurung siku ganda.

```python
MATRIX
```

Baris ini hanya menampilkan nilai tensor matriks tersebut ke konsol atau output lingkungan eksekusi Python. Jika Anda menjalankan kode ini, Anda akan melihat output yang mencetak matriks:

```plaintext
tensor([[ 7,  8],
        [ 9, 10]])
```

Ini adalah representasi tensor matriks PyTorch dengan dua baris dan dua kolom, sesuai dengan nilai yang telah ditentukan.

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Hasil output `tensor([[ 7,  8], [ 9, 10]])` menunjukkan bahwa kita memiliki tensor matriks dalam PyTorch dengan dua baris dan dua kolom. Mari kita jabarkan elemen-elemen dalam output tersebut:

- **`tensor`**: Ini menunjukkan bahwa yang ditampilkan adalah sebuah tensor, yaitu struktur data PyTorch yang dapat menyimpan nilai numerik dalam berbagai dimensi.

- **`[[ 7,  8], [ 9, 10]]`**: Ini adalah nilai-nilai di dalam tensor. Dalam kasus ini, kita memiliki matriks dengan dua baris dan dua kolom. Elemen-elemen ini diurutkan dalam tanda kurung siku ganda sebagai representasi dari tensor matriks.

Jadi, secara keseluruhan, output tersebut memberikan informasi bahwa kita memiliki sebuah tensor matriks dengan dua baris dan dua kolom, dengan nilai-nilai matriks yang sesuai. Dalam PyTorch, ini adalah cara umum untuk menyajikan matriks dalam bentuk tensor.

Wow! More numbers! Matrices are as flexible as vectors, except they've got an extra dimension.



Kode `MATRIX.ndim` mencoba untuk mengakses atribut `ndim` dari tensor `MATRIX`, yang merupakan matriks dalam PyTorch. Perlu diperhatikan bahwa tensor PyTorch tidak memiliki atribut `ndim`. Sebaliknya, kita dapat menggunakan metode `dim()` untuk mendapatkan jumlah dimensi dari tensor.

Sebagai contoh, kita dapat mengganti kode tersebut menjadi:

```python
MATRIX.dim()
```

Jika kita menjalankan kode ini pada tensor `MATRIX` yang telah dibuat sebelumnya (matriks 2x2), kita akan mendapatkan output sebagai berikut:

```plaintext
2
```

Output ini menunjukkan bahwa tensor `MATRIX` memiliki dua dimensi, yang sesuai dengan sifat matriks. Jadi, `MATRIX.dim()` memberikan informasi tentang jumlah dimensi dari tensor matriks tersebut.

In [ ]:
# Check number of dimensions
MATRIX.ndim

2

`MATRIX` has two dimensions (did you count the number of square brakcets on the outside of one side?).

What `shape` do you think it will have?

In [ ]:
MATRIX.shape

torch.Size([2, 2])

We get the output `torch.Size([2, 2])` because `MATRIX` is two elements deep and two elements wide.

How about we create a **tensor**?

Kode ini menciptakan sebuah tensor tiga dimensi dalam PyTorch dengan nilai-nilai yang diberikan. Mari kita bahas penjelasan dari setiap baris kode:

```python
# Membuat tensor tiga dimensi
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
```

Dalam baris ini, kita menggunakan fungsi `torch.tensor()` untuk membuat tensor tiga dimensi. Tensor ini memiliki tiga dimensi dengan ukuran (1, 3, 3). Nilai-nilai tensor ditentukan dalam tiga tingkat tanda kurung siku sebagai representasi dari tensor tiga dimensi.

```python
TENSOR
```

Baris ini hanya menampilkan nilai tensor tersebut ke konsol atau output lingkungan eksekusi Python. Jika Anda menjalankan kode ini, Anda akan melihat output yang mencetak tensor tiga dimensi:

```plaintext
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
```

Ini adalah representasi tensor tiga dimensi PyTorch dengan nilai-nilai yang telah ditentukan. Dalam kasus ini, kita memiliki tensor tiga dimensi dengan ukuran (1, 3, 3).

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Hasil output `tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])` menunjukkan bahwa kita memiliki tensor tiga dimensi dalam PyTorch. Mari kita jabarkan elemen-elemen dalam output tersebut:

- **`tensor`**: Ini menunjukkan bahwa yang ditampilkan adalah sebuah tensor, yaitu struktur data PyTorch yang dapat menyimpan nilai numerik dalam berbagai dimensi.

- **`[[[1, 2, 3], [3, 6, 9], [2, 4, 5]]]`**: Ini adalah nilai-nilai di dalam tensor. Dalam kasus ini, kita memiliki tensor tiga dimensi dengan ukuran (1, 3, 3). Elemen-elemen ini diurutkan dalam tiga tingkat tanda kurung siku sebagai representasi dari tensor tiga dimensi.

Jadi, secara keseluruhan, output tersebut memberikan informasi bahwa kita memiliki sebuah tensor tiga dimensi dengan ukuran (1, 3, 3) dan nilai-nilai tensor yang sesuai. Dalam PyTorch, ini adalah cara umum untuk menyajikan data dengan dimensi yang lebih tinggi, seperti data spasial dalam citra atau deret waktu tiga dimensi.

Woah! What a nice looking tensor.

I want to stress that tensors can represent almost anything.

The one we just created could be the sales numbers for a steak and almond butter store (two of my favourite foods).

![a simple tensor in google sheets showing day of week, steak sales and almond butter sales](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)

How many dimensions do you think it has? (hint: use the square bracket counting trick)

In [ ]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

And what about its shape?

In [ ]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Alright, it outputs `torch.Size([1, 3, 3])`.

The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

> **Note:** You might've noticed me using lowercase letters for `scalar` and `vector` and uppercase letters for `MATRIX` and `TENSOR`. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as `y` or `a`. And matrices and tensors denoted as uppercase letters such as `X` or `W`.
>
> You also might notice the names martrix and tensor used interchangably. This is common. Since in PyTorch you're often dealing with `torch.Tensor`s (hence the tensor name), however, the shape and dimensions of what's inside will dictate what it actually is.

Let's summarise.

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) |
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) |

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Random tensors

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) and passing in the `size` parameter.

```python
# Membuat tensor acak dengan ukuran (3, 4)
random_tensor = torch.rand(size=(3, 4))
```
Baris ini menciptakan tensor acak menggunakan fungsi `torch.rand()`. `size=(3, 4)` menentukan ukuran tensor yang dibuat, yaitu 3 baris dan 4 kolom.

```python
random_tensor.dtype
```
Baris ini mengakses atribut `dtype` dari tensor `random_tensor`. `dtype` adalah tipe data dari elemen tensor. Hasilnya akan memberikan informasi tentang tipe data yang digunakan untuk merepresentasikan nilai-nilai dalam tensor tersebut.

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6541, 0.4807, 0.2162, 0.6168],
         [0.4428, 0.6608, 0.6194, 0.8620],
         [0.2795, 0.6055, 0.4958, 0.5483]]),
 torch.float32)

Hasil output yang disediakan adalah tupel yang terdiri dari dua elemen:

1. **`tensor([[0.6541, 0.4807, 0.2162, 0.6168], [0.4428, 0.6608, 0.6194, 0.8620], [0.2795, 0.6055, 0.4958, 0.5483]])`**:
   - Ini adalah tensor PyTorch dengan ukuran (3, 4), yang diisi dengan nilai-nilai acak yang dihasilkan oleh fungsi `torch.rand()` dengan tipe data `torch.float32`. Setiap nilai dalam tensor ini adalah angka acak yang dihasilkan secara acak dari distribusi seragam antara 0 dan 1.

2. **`torch.float32`**:
   - Ini adalah tipe data dari elemen dalam tensor. Dalam hal ini, tensor tersebut menggunakan tipe data float32, yang merupakan tipe data floating-point 32-bit. Ini mengindikasikan bahwa setiap elemen dalam tensor menyimpan nilai floating-point dengan presisi 32-bit.

The flexibility of `torch.rand()` is that we can adjust the `size` to be whatever we want.

For example, say you wanted a random tensor in the common image shape of `[224, 224, 3]` (`[height, width, color_channels`]).

```python
# Membuat tensor acak dengan ukuran (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
```
Baris ini menciptakan tensor acak menggunakan fungsi `torch.rand()`. `size=(224, 224, 3)` menentukan ukuran tensor yang dibuat, yaitu dengan dimensi 224 (tinggi), 224 (lebar), dan 3 (kedalaman). Dalam konteks ini, ukuran tensor mencerminkan representasi sederhana dari citra dengan tinggi, lebar, dan saluran warna.

```python
random_image_size_tensor.shape, random_image_size_tensor.ndim
```
Baris ini mengakses atribut `shape` dan metode `ndim` dari tensor `random_image_size_tensor`.
- `shape` memberikan informasi tentang ukuran atau dimensi tensor, dalam hal ini, `(224, 224, 3)`.
- `ndim` memberikan jumlah dimensi tensor, dalam hal ini, `3`.

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Hasil output yang disediakan adalah tupel yang terdiri dari dua elemen:

1. **`torch.Size([224, 224, 3])`**:
   - Ini adalah representasi dari ukuran tensor. Dalam hal ini, ukuran tensor adalah (224, 224, 3), yang berarti tensor memiliki tiga dimensi dengan masing-masing dimensi memiliki ukuran 224. Dalam konteks ini, ini sering digunakan untuk merepresentasikan citra dengan tinggi 224 piksel, lebar 224 piksel, dan 3 saluran warna (RGB).

2. **`3`**:
   - Ini adalah jumlah dimensi dari tensor, yaitu 3. Sesuai dengan informasi dalam ukuran tensor, kita tahu bahwa tensor ini memiliki tiga dimensi, masing-masing mewakili tinggi, lebar, dan saluran warna citra.

### Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html)

Again, the `size` parameter comes into play.

```python
# Membuat tensor dengan semua elemen bernilai nol
zeros = torch.zeros(size=(3, 4))
```
Baris ini menggunakan fungsi `torch.zeros()` untuk membuat tensor yang berisi semua elemen nol. `size=(3, 4)` menentukan ukuran tensor yang dibuat, yaitu dengan 3 baris dan 4 kolom.

```python
zeros.dtype
```
Baris ini mengakses atribut `dtype` dari tensor `zeros`. `dtype` memberikan informasi tentang tipe data dari elemen tensor. Hasilnya akan memberikan informasi tentang tipe data yang digunakan untuk merepresentasikan nilai-nilai dalam tensor tersebut. Dalam hal ini, tipe data tensor adalah float32, yang merupakan tipe data floating-point 32-bit.

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

Hasil output yang disediakan adalah tupel yang terdiri dari dua elemen:

1. **`tensor([[0., 0., 0., 0.], [0., 0., 0., 0.], [0., 0., 0., 0.]])`**:
   - Ini adalah tensor PyTorch dengan ukuran (3, 4), yang diisi dengan semua elemen bernilai nol. Elemen-elemen dalam tensor ini adalah angka nol dengan tipe data float32.

2. **`torch.float32`**:
   - Ini adalah tipe data dari elemen dalam tensor. Dalam hal ini, tensor tersebut menggunakan tipe data float32, yang merupakan tipe data floating-point 32-bit. Ini mengindikasikan bahwa setiap elemen dalam tensor menyimpan nilai floating-point dengan presisi 32-bit.

We can do the same to create a tensor of all ones except using [`torch.ones()` ](https://pytorch.org/docs/stable/generated/torch.ones.html) instead.

```python
# Membuat tensor dengan semua elemen bernilai satu
ones = torch.ones(size=(3, 4))
```
Baris ini menggunakan fungsi `torch.ones()` untuk membuat tensor yang berisi semua elemen bernilai satu. `size=(3, 4)` menentukan ukuran tensor yang dibuat, yaitu dengan 3 baris dan 4 kolom.

```python
ones.dtype
```
Baris ini mengakses atribut `dtype` dari tensor `ones`. `dtype` memberikan informasi tentang tipe data dari elemen tensor. Hasilnya akan memberikan informasi tentang tipe data yang digunakan untuk merepresentasikan nilai-nilai dalam tensor tersebut. Dalam hal ini, tipe data tensor adalah float32, yang merupakan tipe data floating-point 32-bit.

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Hasil output yang disediakan adalah tupel yang terdiri dari dua elemen:

1. **`tensor([[1., 1., 1., 1.], [1., 1., 1., 1.], [1., 1., 1., 1.]])`**:
   - Ini adalah tensor PyTorch dengan ukuran (3, 4), yang diisi dengan semua elemen bernilai satu. Elemen-elemen dalam tensor ini adalah angka satu dengan tipe data float32.

2. **`torch.float32`**:
   - Ini adalah tipe data dari elemen dalam tensor. Dalam hal ini, tensor tersebut menggunakan tipe data float32, yang merupakan tipe data floating-point 32-bit. Ini mengindikasikan bahwa setiap elemen dalam tensor menyimpan nilai floating-point dengan presisi 32-bit.

### Creating a range and tensors like

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

Where:
* `start` = start of range (e.g. 0)
* `end` = end of range (e.g. 10)
* `step` = how many steps in between each value (e.g. 1)

> **Note:** In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an error in the future.

```python
# Menggunakan torch.range() yang sudah tidak direkomendasikan (deprecated)
zero_to_ten_deprecated = torch.range(0, 10) # Catatan: ini mungkin menghasilkan error di masa depan
```
Baris ini mencoba membuat tensor yang berisi rentang nilai dari 0 hingga 10 menggunakan fungsi `torch.range()`. Namun, perlu dicatat bahwa metode ini sudah tidak direkomendasikan (deprecated) dan mungkin akan menghasilkan error di masa depan.

```python
# Membuat rentang nilai dari 0 hingga 10 dengan menggunakan torch.arange()
zero_to_ten = torch.arange(start=0, end=10, step=1)
```
Baris ini menggunakan fungsi `torch.arange()` untuk membuat tensor yang berisi rentang nilai dari 0 hingga 10. Fungsi ini lebih disarankan daripada `torch.range()`. Argumen `start` menunjukkan nilai awal, `end` menunjukkan nilai akhir, dan `step` menunjukkan jarak antar nilai dalam rentang. Dalam hal ini, kita membuat rentang dengan nilai awal 0, nilai akhir 10, dan langkah sebesar 1.

In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipykernel_3695928/193451495.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Hasil output termasuk pesan peringatan (UserWarning) dan nilai tensor. Mari kita jelaskan keduanya:

1. **Pesan Peringatan (UserWarning):**
   - Pesan peringatan ini memberi tahu pengguna bahwa fungsi `torch.range()` sudah tidak direkomendasikan (deprecated) dan akan dihapus dalam rilis mendatang. Hal ini dikarenakan perilakunya tidak konsisten dengan fungsi bawaan Python, `range()`. Pesan ini menyarankan untuk menggunakan `torch.arange()` sebagai penggantinya.

2. **Nilai Tensor:**
   - Nilai tensor yang dicetak adalah hasil dari pemanggilan `torch.arange(start=0, end=10, step=1)`, yang menghasilkan tensor berisi rentang nilai dari 0 hingga 9 (karena `end` adalah eksklusif) dengan langkah sebesar 1. Dalam hal ini, tensor tersebut adalah `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`.

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

```python
# Membuat tensor nol dengan bentuk yang sama seperti tensor lainnya
ten_zeros = torch.zeros_like(input=zero_to_ten)
```
Baris ini menggunakan fungsi `torch.zeros_like()` untuk membuat tensor yang berisi semua elemen bernilai nol, tetapi dengan bentuk (shape) yang sama seperti tensor `zero_to_ten`. Fungsi ini mengambil tensor yang diberikan (`zero_to_ten` dalam hal ini) sebagai argumen input dan menghasilkan tensor yang memiliki bentuk yang sama, tetapi elemennya diisi dengan nol.

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Output tersebut adalah hasil dari pembuatan tensor menggunakan `torch.zeros_like(input=zero_to_ten)`. Berikut penjelasannya:

- **`tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])`**:
   - Ini adalah tensor PyTorch yang berisi sepuluh elemen, dan semua elemennya diisi dengan nilai nol. Bentuk (shape) tensor ini sama dengan bentuk tensor `zero_to_ten`, karena kita menggunakan `torch.zeros_like()` untuk membuat tensor baru yang mengikuti bentuk tensor yang diberikan (`zero_to_ten`). Sebagai contoh, jika `zero_to_ten` memiliki bentuk (shape) (m, n), maka `ten_zeros` juga akan memiliki bentuk (shape) (m, n), dan semua elemennya akan bernilai nol.

### Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

> **Note:** An integer is a flat round number like `7` whereas a float has a decimal `7.0`.

The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

> **Resources:**
  * See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Read the [Wikipedia page for an overview of what precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the `dtype` parameter.

```python
# Membuat tensor dengan tipe data float32 secara default
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # Defaults to None, which uses the default tensor type
                               requires_grad=False) # If True, operations performed on the tensor are recorded
```
Baris ini menggunakan fungsi `torch.tensor()` untuk membuat tensor. Dalam hal ini, kita memberikan daftar nilai `[3.0, 6.0, 9.0]` sebagai argumen. Tipe data tensor secara default diatur sebagai float32 jika tidak diberikan. Argumen `dtype=None` mengikuti default dan akan menghasilkan tensor dengan tipe data float32. Argumen `device=None` mengikuti default dan akan menggunakan tipe tensor default pada perangkat yang tersedia. Argumen `requires_grad=False` menetapkan apakah operasi yang dilakukan pada tensor akan direkam untuk perhitungan gradien (backpropagation) saat pelatihan model.

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Hasil output yang diberikan adalah tupel yang terdiri dari tiga elemen:

1. **`torch.Size([3])`**:
   - Ini adalah representasi dari ukuran (shape) tensor. Dalam hal ini, tensor memiliki satu dimensi dengan panjang (length) 3. Bentuk ini mencerminkan bahwa tensor ini adalah vektor dengan tiga elemen.

2. **`torch.float32`**:
   - Ini adalah tipe data dari elemen dalam tensor. Dalam hal ini, tipe data tensor adalah float32, yang merupakan tipe data floating-point 32-bit.

3. **`device(type='cpu')`**:
   - Ini adalah informasi tentang perangkat tempat tensor disimpan. Dalam hal ini, tensor disimpan di CPU (`'cpu'`). Jika Anda memiliki GPU yang tersedia, Anda dapat memindahkan tensor ke GPU untuk pemrosesan yang lebih cepat dengan menggunakan metode `.to('cuda')` atau `.cuda()`.

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is `torch.float32` and the other is `torch.float16` (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

We'll see more of this device talk later on.

For now let's create a tensor with `dtype=torch.float16`.

```python
# Membuat tensor dengan tipe data float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work
```

Baris ini menggunakan fungsi `torch.tensor()` untuk membuat tensor dengan tipe data float16. Argumen `dtype=torch.float16` secara eksplisit menetapkan tipe data tensor sebagai float16, yang merupakan tipe data floating-point 16-bit. Alternatifnya, kita bisa menggunakan `dtype=torch.half`, karena `torch.half` juga merujuk pada tipe data float16. Dengan menggunakan tipe data float16, kita mengurangi presisi bilangan floating-point, tetapi mengurangi penggunaan memori dan dapat mempercepat operasi pada perangkat keras yang mendukung float16.

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

`torch.float16` adalah representasi dari tipe data floating-point 16-bit (float16) dalam PyTorch. Jika Anda mencetak `torch.float16`, hasilnya akan menjadi:

```
torch.float16
```

Output ini menunjukkan bahwa `torch.float16` adalah suatu objek atau tipe data yang dapat digunakan untuk menyatakan bahwa suatu tensor dalam PyTorch menggunakan representasi floating-point dengan presisi 16-bit. Tipe data float16 sering digunakan untuk mengoptimalkan penggunaan memori dan percepatan operasi pada perangkat keras yang mendukung operasi float16.

## Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

```python
# Membuat tensor acak dengan ukuran 3x4
some_tensor = torch.rand(3, 4)
```
Baris ini membuat tensor acak dengan ukuran 3 baris dan 4 kolom menggunakan fungsi `torch.rand()`. Nilai-nilai dalam tensor ini diinisialisasi dengan angka acak antara 0 dan 1.

```python
# Menampilkan detail tensor
print(some_tensor)
```
Baris ini mencetak nilai tensor ke konsol atau output lingkungan eksekusi Python.

```python
# Menampilkan bentuk (shape) tensor
print(f"Shape of tensor: {some_tensor.shape}")
```
Baris ini mencetak bentuk (shape) tensor ke konsol. Bentuk tensor menunjukkan jumlah dimensi dan ukuran setiap dimensinya.

```python
# Menampilkan tipe data (datatype) tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
```
Baris ini mencetak tipe data (datatype) tensor ke konsol. Ini memberikan informasi tentang jenis nilai yang dapat disimpan dalam tensor (misalnya, float32, float16, dll.).

```python
# Menampilkan perangkat (device) tempat tensor disimpan
print(f"Device tensor is stored on: {some_tensor.device}") # akan default ke CPU
```
Baris ini mencetak informasi perangkat (device) tempat tensor disimpan. Jika tidak disebutkan, secara default tensor akan disimpan di CPU. Jika Anda memiliki GPU dan ingin menggunakan GPU untuk pemrosesan, Anda dapat menggunakan metode `.to('cuda')` atau `.cuda()` untuk memindahkan tensor ke GPU.

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4688, 0.0055, 0.8551, 0.0646],
        [0.6538, 0.5157, 0.4071, 0.2109],
        [0.9960, 0.3061, 0.9369, 0.7008]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Hasil output yang diberikan adalah hasil dari eksekusi baris kode yang telah dijelaskan sebelumnya. Berikut adalah penjelasan untuk hasil output tersebut:

- **`tensor([[0.4688, 0.0055, 0.8551, 0.0646], [0.6538, 0.5157, 0.4071, 0.2109], [0.9960, 0.3061, 0.9369, 0.7008]])`**:
   - Ini adalah representasi dari nilai tensor. Tensor ini memiliki bentuk 3x4, dengan nilai-nilai yang diinisialisasi secara acak antara 0 dan 1.

- **`Shape of tensor: torch.Size([3, 4])`**:
   - Ini adalah bentuk (shape) dari tensor. Bentuk ini menunjukkan bahwa tensor memiliki dua dimensi, dengan panjang dimensi pertama 3 dan panjang dimensi kedua 4.

- **`Datatype of tensor: torch.float32`**:
   - Ini adalah tipe data (datatype) dari elemen dalam tensor. Dalam hal ini, tipe data tensor adalah float32, yang merupakan tipe data floating-point 32-bit.

- **`Device tensor is stored on: CPU`**:
   - Ini adalah informasi tentang perangkat (device) tempat tensor disimpan. Pada contoh ini, tensor disimpan di CPU. Jika Anda memiliki GPU yang tersedia, Anda dapat menggunakan metode `.to('cuda')` atau `.cuda()` untuk memindahkan tensor ke GPU.

> **Note:** When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":
  * "*what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where*"

## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

### Basic operations

Let's start with a few of the fundamental operations, addition (`+`), subtraction (`-`), mutliplication (`*`).

They work just as you think they would.

```python
# Membuat tensor dengan nilai tertentu
tensor = torch.tensor([1, 2, 3])
```
Baris ini membuat tensor dengan nilai `[1, 2, 3]` menggunakan fungsi `torch.tensor()`.

```python
# Menambahkan nilai ke setiap elemen dalam tensor
tensor + 10
```
Baris ini menambahkan nilai 10 ke setiap elemen dalam tensor. Operasi ini disebut penambahan skalar, di mana skalar (dalam hal ini, 10) ditambahkan ke setiap elemen dalam tensor. Hasilnya adalah tensor baru dengan nilai `[11, 12, 13]`. Perhatikan bahwa tensor asli tidak berubah, dan hasil penambahan ini hanya ditampilkan atau dapat disimpan dalam variabel baru jika diinginkan.

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

Hasil output `tensor([11, 12, 13])` menunjukkan tensor baru yang dihasilkan setelah operasi penambahan skalar. Berikut penjelasan elemen-elemen output tersebut:

- **`tensor`**: Ini menunjukkan bahwa yang ditampilkan adalah sebuah tensor, yaitu struktur data PyTorch yang dapat menyimpan nilai numerik dalam berbagai dimensi.

- **`[11, 12, 13]`**: Ini adalah nilai-nilai di dalam tensor. Dalam kasus ini, nilai-nilai tersebut dihasilkan setelah menambahkan skalar 10 ke setiap elemen dalam tensor awal `[1, 2, 3]`. Hasilnya adalah tensor baru dengan nilai `[11, 12, 13]`.

Jadi, secara keseluruhan, output tersebut memperlihatkan hasil dari operasi penambahan skalar pada setiap elemen dalam tensor awal.

```python
# Mengalikan setiap elemen dalam tensor dengan 10
tensor * 10
```
Baris ini melakukan operasi perkalian skalar pada setiap elemen dalam tensor. Dalam hal ini, setiap elemen dalam tensor awal (`tensor`) dikalikan dengan skalar 10. Hasilnya adalah tensor baru dengan nilai setiap elemen yang diperoleh dari perkalian elemen-elemen tensor awal dengan 10. Perhatikan bahwa tensor asli tidak berubah, dan hasil perkalian ini hanya ditampilkan atau dapat disimpan dalam variabel baru jika diinginkan.

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Hasil output `tensor([10, 20, 30])` menunjukkan tensor baru yang dihasilkan setelah operasi perkalian skalar. Berikut penjelasan elemen-elemen output tersebut:

- **`tensor`**: Ini menunjukkan bahwa yang ditampilkan adalah sebuah tensor, yaitu struktur data PyTorch yang dapat menyimpan nilai numerik dalam berbagai dimensi.

- **`[10, 20, 30]`**: Ini adalah nilai-nilai di dalam tensor. Dalam kasus ini, nilai-nilai tersebut dihasilkan setelah melakukan operasi perkalian skalar dengan nilai 10 pada setiap elemen dalam tensor awal `[1, 2, 3]`. Hasilnya adalah tensor baru dengan nilai `[10, 20, 30]`.

Jadi, secara keseluruhan, output tersebut memperlihatkan hasil dari operasi perkalian skalar pada setiap elemen dalam tensor awal.

Notice how the tensor values above didn't end up being `tensor([110, 120, 130])`, this is because the values inside the tensor don't change unless they're reassigned.

```python
# Memeriksa nilai tensor tanpa reassign (tanpa menyimpan perubahan)
tensor
```

Baris ini mencetak nilai tensor tanpa melakukan reassign, yang berarti tensor `tensor` tetap memiliki nilai yang sama seperti sebelumnya (`[1, 2, 3]`). Perubahan atau operasi yang dilakukan pada tensor tidak mempengaruhi nilai tensor asli kecuali jika hasilnya disimpan atau tensor diassign kembali ke variabel. Dalam kasus ini, nilai tensor tetap `[10, 20, 30]`.

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

Hasil output `tensor([1, 2, 3])` menunjukkan nilai tensor yang terakhir kali diinisialisasi sebelumnya atau hasil dari operasi tanpa reassign. Berikut penjelasannya:

- **`tensor`**: Ini menunjukkan bahwa yang ditampilkan adalah sebuah tensor, yaitu struktur data PyTorch yang dapat menyimpan nilai numerik dalam berbagai dimensi.

- **`[1, 2, 3]`**: Ini adalah nilai-nilai di dalam tensor. Dalam kasus ini, nilai-nilai tersebut adalah nilai tensor yang terakhir kali diinisialisasi sebelumnya, yaitu `[1, 2, 3]`. Perhatikan bahwa nilai ini tidak berubah karena hasil operasi sebelumnya tidak disimpan atau tensor tidak diassign kembali ke variabel.

Let's subtract a number and this time we'll reassign the `tensor` variable.

```python
# Mengurangkan setiap elemen dalam tensor dengan 10 dan mengassign kembali
tensor = tensor - 10
```

Baris ini melakukan operasi pengurangan skalar pada setiap elemen dalam tensor. Dalam hal ini, setiap elemen dalam tensor `tensor` dikurangkan dengan skalar 10. Hasilnya kemudian diassign kembali ke variabel `tensor`. Setelah operasi ini, nilai tensor sekarang adalah hasil pengurangan tersebut. Perubahan nilai tensor terjadi karena hasil operasi dikembalikan dan diassign kembali ke variabel `tensor`.

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

Hasil output `tensor([-9, -8, -7])` menunjukkan nilai tensor yang dihasilkan setelah operasi pengurangan skalar dan reassign. Berikut penjelasan elemen-elemen output tersebut:

- **`tensor`**: Ini menunjukkan bahwa yang ditampilkan adalah sebuah tensor, yaitu struktur data PyTorch yang dapat menyimpan nilai numerik dalam berbagai dimensi.

- **`[-9, -8, -7]`**: Ini adalah nilai-nilai di dalam tensor. Dalam kasus ini, nilai-nilai tersebut dihasilkan setelah melakukan operasi pengurangan skalar dengan nilai 10 pada setiap elemen dalam tensor sebelumnya `[1, 2, 3]`. Hasilnya adalah tensor baru dengan nilai `[-9, -8, -7]`. Perhatikan bahwa nilai tensor telah berubah setelah operasi ini karena hasil operasi tersebut diassign kembali ke variabel `tensor`.

```python
# Menambahkan setiap elemen dalam tensor dengan 10 dan mengassign kembali
tensor = tensor + 10
```

Baris ini melakukan operasi penambahan skalar pada setiap elemen dalam tensor. Dalam hal ini, setiap elemen dalam tensor `tensor` ditambahkan dengan skalar 10. Hasilnya kemudian diassign kembali ke variabel `tensor`. Setelah operasi ini, nilai tensor sekarang adalah hasil penambahan tersebut. Perubahan nilai tensor terjadi karena hasil operasi dikembalikan dan diassign kembali ke variabel `tensor`.

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

Hasil output `tensor([1, 2, 3])` menunjukkan nilai tensor yang dihasilkan setelah operasi penambahan skalar dan reassign. Berikut penjelasan elemen-elemen output tersebut:

- **`tensor`**: Ini menunjukkan bahwa yang ditampilkan adalah sebuah tensor, yaitu struktur data PyTorch yang dapat menyimpan nilai numerik dalam berbagai dimensi.

- **`[1, 2, 3]`**: Ini adalah nilai-nilai di dalam tensor. Dalam kasus ini, nilai-nilai tersebut dihasilkan setelah melakukan operasi penambahan skalar dengan nilai 10 pada setiap elemen dalam tensor sebelumnya `[-9, -8, -7]`. Hasilnya adalah tensor baru dengan nilai `[1, 2, 3]`. Perhatikan bahwa nilai tensor telah berubah setelah operasi ini karena hasil operasi tersebut diassign kembali ke variabel `tensor`.

PyTorch also has a bunch of built-in functions like [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (short for multiplication) and [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) to perform basic operations.

```python
# Menggunakan fungsi torch.multiply() untuk mengalikan setiap elemen dalam tensor dengan 10
torch.multiply(tensor, 10)
```

Baris ini menggunakan fungsi `torch.multiply()` untuk mengalikan setiap elemen dalam tensor `tensor` dengan skalar 10. Fungsi ini memproses elemen-elemen tensor secara elemen demi elemen, sehingga menghasilkan tensor baru dengan nilai-nilai yang merupakan hasil perkalian skalar. Perlu diperhatikan bahwa nilai tensor asli tidak berubah, dan hasil perkalian ini hanya ditampilkan atau dapat disimpan dalam variabel baru jika diinginkan.

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

However, it's more common to use the operator symbols like `*` instead of `torch.mul()`

```python
# Operasi perkalian elemen-wise (setiap elemen mengalikan elemennya yang setara, indeks 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
```

Baris ini mencetak operasi perkalian elemen-wise dari tensor `tensor` dengan dirinya sendiri. Ini dilakukan dengan menggunakan operator `*` antara dua tensor, sehingga setiap elemen pada posisi indeks yang sama dikalikan bersama. Misalnya, elemen pada indeks 0 akan dikalikan dengan elemen pada indeks 0, dan seterusnya.

```python
# Menampilkan hasil perkalian elemen-wise
print("Equals:", tensor * tensor)
```

Baris ini mencetak hasil dari operasi perkalian elemen-wise, yang menghasilkan tensor baru dengan nilai-nilai yang merupakan hasil perkalian setiap elemen dengan dirinya sendiri. Ini adalah contoh dari operasi elemen-wise, di mana setiap elemen pada posisi indeks yang sama dalam tensor dikalikan bersama.

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Hasil output `tensor([1, 2, 3]) * tensor([1, 2, 3])` dan `Equals: tensor([1, 4, 9])` menunjukkan operasi perkalian elemen-wise dari dua tensor yang memiliki nilai yang sama. Berikut penjelasannya:

- **`tensor([1, 2, 3]) * tensor([1, 2, 3])`**:
  - Ini adalah representasi dari operasi perkalian elemen-wise antara dua tensor. Setiap elemen pada posisi indeks yang sama dari tensor pertama dikalikan dengan elemen pada posisi indeks yang sama dari tensor kedua. Hasilnya adalah tensor baru `[1, 4, 9]`.

- **`Equals: tensor([1, 4, 9])`**:
  - Ini adalah hasil dari operasi perkalian elemen-wise tersebut. Hasilnya adalah tensor baru dengan nilai-nilai `[1, 4, 9]`. Setiap elemen pada tensor ini adalah hasil dari perkalian elemen yang setara pada tensor asli `[1, 2, 3]`.

### Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Note:** "`@`" in Python is the symbol for matrix multiplication.

> **Resource:** You can see all of the rules for matrix multiplication using `torch.matmul()` [in the PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.



```python
# Mengimport library PyTorch
import torch
```

Baris ini mengimport library PyTorch ke dalam sesi Python. Library ini digunakan untuk operasi tensor dan komputasi numerik dalam konteks machine learning dan deep learning.

```python
# Membuat tensor dengan nilai [1, 2, 3]
tensor = torch.tensor([1, 2, 3])
```

Baris ini membuat tensor dengan nilai `[1, 2, 3]` menggunakan fungsi `torch.tensor()`.

```python
# Menampilkan bentuk (shape) tensor
tensor.shape
```

Baris ini mengakses atribut `shape` dari tensor, yang memberikan informasi tentang bentuk atau dimensi dari tensor. Dalam kasus ini, kita ingin mengetahui bentuk tensor `[1, 2, 3]`. Outputnya akan memberikan informasi tentang jumlah dimensi dan ukuran setiap dimensinya, misalnya `(3,)`.

In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Hasil output `torch.Size([3])` menunjukkan bentuk (shape) dari tensor yang telah diakses dengan atribut `shape`. Berikut penjelasannya:

- **`torch.Size([3])`**:
   - Ini adalah representasi bentuk (shape) dari tensor. Dalam konteks ini, tensor memiliki satu dimensi dengan panjang (length) 3. Bentuk ini dinyatakan dalam bentuk tuple, dan `(3,)` menunjukkan bahwa tensor ini adalah vektor dengan tiga elemen.

Dengan kata lain, output ini memberikan informasi tentang struktur dimensi dari tensor, dan dalam hal ini, tensor memiliki satu dimensi dengan panjang 3.

The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our `tensor` variable with values `[1, 2, 3]`:

| Operation | Calculation | Code |
| ----- | ----- | ----- |
| **Element-wise multiplication** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Matrix multiplication** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |


In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

You can do matrix multiplication by hand but it's not recommended.

The in-built `torch.matmul()` method is faster.

```python
%%time
```

Baris ini adalah magic command untuk mengukur waktu eksekusi dari sel kode yang berada di bawahnya.

```python
# Inisialisasi nilai awal
value = 0
```

Baris ini mendeklarasikan dan menginisialisasi variabel `value` dengan nilai awal 0. Variabel ini akan digunakan untuk menyimpan hasil perkalian dan penjumlahan.

```python
# Melakukan perulangan untuk menghitung hasil perkalian dan penjumlahan
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
```

Baris ini menggunakan perulangan `for` untuk mengakses setiap elemen dalam tensor dan melakukan operasi perkalian elemen dengan dirinya sendiri (`tensor[i] * tensor[i]`). Hasil perkalian tersebut kemudian ditambahkan ke variabel `value`.

```python
# Menampilkan hasil akhir dari perhitungan
value
```

Baris ini mencetak nilai akhir dari variabel `value`, yang merupakan hasil dari operasi perkalian dan penjumlahan elemen dalam tensor secara manual.

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 773 µs, sys: 0 ns, total: 773 µs
Wall time: 499 µs


tensor(14)

Hasil output yang diberikan setelah magic command `%%time` menunjukkan waktu eksekusi dari seluruh sel kode yang berada di bawahnya. Berikut penjelasan elemen-elemen output tersebut:

- **`CPU times: user 773 µs, sys: 0 ns, total: 773 µs`**:
  - Ini adalah waktu CPU yang diukur selama eksekusi. Terdapat tiga komponen:
    - `user`: Waktu CPU yang dihabiskan oleh proses pengguna atau kode yang dieksekusi.
    - `sys`: Waktu CPU yang dihabiskan oleh sistem atau kode yang dieksekusi oleh kernel.
    - `total`: Jumlah total waktu CPU yang digunakan oleh proses dan sistem.

- **`Wall time: 499 µs`**:
  - Ini adalah waktu sebenarnya yang diukur dari awal hingga akhir eksekusi, yang mencakup waktu tunggu (waiting) dan waktu CPU.

- **`tensor(14)`**:
  - Ini adalah hasil dari perhitungan yang dilakukan di dalam loop. Nilai 14 mewakili hasil dari operasi perkalian dan penjumlahan elemen dalam tensor secara manual.

```python
%%time
```

Baris ini adalah magic command untuk mengukur waktu eksekusi dari sel kode yang berada di bawahnya.

```python
# Menggunakan fungsi torch.matmul() untuk melakukan perkalian matriks
torch.matmul(tensor, tensor)
```

Baris ini menggunakan fungsi `torch.matmul()` untuk melakukan perkalian matriks dari tensor `tensor` dengan dirinya sendiri. Fungsi ini mengimplementasikan perkalian matriks dalam konteks PyTorch, dan hasilnya adalah tensor baru yang merupakan hasil dari operasi perkalian matriks. Perlu dicatat bahwa penggunaan fungsi bawaan seperti `torch.matmul()` lebih disukai daripada mengimplementasikan operasi matriks secara manual dengan menggunakan loop `for`, karena lebih efisien dan dioptimalkan untuk perhitungan tensor dalam PyTorch.

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 146 µs, sys: 83 µs, total: 229 µs
Wall time: 171 µs


tensor(14)

Hasil output yang diberikan setelah magic command `%%time` menunjukkan waktu eksekusi dari seluruh sel kode yang berada di bawahnya. Berikut penjelasan elemen-elemen output tersebut:

- **`CPU times: user 146 µs, sys: 83 µs, total: 229 µs`**:
  - Ini adalah waktu CPU yang diukur selama eksekusi. Terdapat tiga komponen:
    - `user`: Waktu CPU yang dihabiskan oleh proses pengguna atau kode yang dieksekusi.
    - `sys`: Waktu CPU yang dihabiskan oleh sistem atau kode yang dieksekusi oleh kernel.
    - `total`: Jumlah total waktu CPU yang digunakan oleh proses dan sistem.

- **`Wall time: 171 µs`**:
  - Ini adalah waktu sebenarnya yang diukur dari awal hingga akhir eksekusi, yang mencakup waktu tunggu (waiting) dan waktu CPU.

- **`tensor(14)`**:
  - Ini adalah hasil dari operasi perkalian matriks yang dilakukan dengan menggunakan fungsi `torch.matmul()`. Nilai 14 mewakili hasil dari operasi perkalian dan penjumlahan elemen dalam tensor secara efisien dengan menggunakan fungsi bawaan PyTorch.

## One of the most common errors in deep learning (shape errors)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

```python
# Membuat tensor_A dengan bentuk (3, 2)
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
```

Baris ini membuat tensor_A dengan bentuk (shape) (3, 2), yang berarti tensor ini memiliki 3 baris dan 2 kolom. Ini dilakukan dengan menggunakan fungsi `torch.tensor()` dan menyediakan nilai-nilai serta tipe data tensor.

```python
# Membuat tensor_B dengan bentuk (3, 2)
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
```

Baris ini membuat tensor_B dengan bentuk (shape) (3, 2), yang sama dengan bentuk tensor_A. Ini juga dilakukan dengan menggunakan fungsi `torch.tensor()` dan menyediakan nilai-nilai serta tipe data tensor.

```python
# Melakukan operasi perkalian matriks antara tensor_A dan tensor_B
torch.matmul(tensor_A, tensor_B) # (ini akan menghasilkan error)
```

Baris ini mencoba melakukan operasi perkalian matriks antara tensor_A dan tensor_B menggunakan fungsi `torch.matmul()`. Namun, karena bentuk tensor_A adalah (3, 2) dan bentuk tensor_B adalah (3, 2), operasi perkalian matriks tidak dapat dilakukan, dan ini akan menghasilkan error. Untuk melakukan operasi perkalian matriks, jumlah kolom dalam tensor_A harus sama dengan jumlah baris dalam tensor_B. Dalam kasus ini, jumlah kolom tensor_A adalah 2, sedangkan jumlah baris tensor_B adalah 3, sehingga operasi perkalian matriks tidak dapat dilakukan.

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Error `RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)` terjadi karena tensor_A dan tensor_B memiliki bentuk (shape) yang tidak memenuhi aturan perkalian matriks.

Pada umumnya, untuk melakukan perkalian matriks, jumlah kolom pada matriks pertama harus sama dengan jumlah baris pada matriks kedua. Dalam hal ini, tensor_A memiliki bentuk (3, 2), yang berarti memiliki 3 baris dan 2 kolom, dan tensor_B juga memiliki bentuk (3, 2) dengan 3 baris dan 2 kolom.

Operasi perkalian matriks tidak dapat dilakukan jika jumlah kolom pada matriks pertama tidak sama dengan jumlah baris pada matriks kedua. Dalam kasus ini, keduanya memiliki jumlah kolom dan baris yang sama (yaitu 2), sehingga operasi perkalian matriks tidak dapat dilakukan dan menyebabkan error.

Untuk dapat melakukan perkalian matriks, salah satu dari tensor_A atau tensor_B perlu diubah bentuknya sehingga jumlah kolom pada matriks pertama sama dengan jumlah baris pada matriks kedua. Misalnya, jika ingin melakukan perkalian matriks dengan urutan tensor_A * tensor_B, maka bentuk tensor_B dapat diubah menjadi (2, 3) agar perkalian matriks dapat dilakukan dengan benar.

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:
* `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* `tensor.T` - where `tensor` is the desired tensor to transpose.

Let's try the latter.

```python
# Menampilkan isi dari tensor_A
print(tensor_A)
```

Baris ini mencetak isi dari tensor_A menggunakan fungsi `print()`. Ini digunakan untuk menampilkan nilai dan bentuk tensor_A dalam format yang lebih mudah dibaca.

```python
# Menampilkan isi dari tensor_B
print(tensor_B)
```

Baris ini mencetak isi dari tensor_B menggunakan fungsi `print()`. Ini digunakan untuk menampilkan nilai dan bentuk tensor_B dalam format yang lebih mudah dibaca.

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


Hasil output yang diberikan adalah nilai-nilai dari tensor_A dan tensor_B. Berikut penjelasan untuk masing-masing hasil output:

- **`tensor([[1., 2.], [3., 4.], [5., 6.]])`**:
  - Ini adalah isi dari tensor_A. Tensor_A adalah matriks dengan bentuk (3, 2), yang berarti memiliki 3 baris dan 2 kolom. Nilai-nilai matriksnya adalah:
    ```
    1.  2.
    3.  4.
    5.  6.
    ```

- **`tensor([[7., 10.], [8., 11.], [9., 12.]])`**:
  - Ini adalah isi dari tensor_B. Tensor_B juga merupakan matriks dengan bentuk (3, 2), yang memiliki 3 baris dan 2 kolom. Nilai-nilai matriksnya adalah:
    ```
    7. 10.
    8. 11.
    9. 12.
    ```

Output ini memperlihatkan nilai-nilai matriks untuk tensor_A dan tensor_B.

```python
# Menampilkan isi dari tensor_A
print(tensor_A)
```

Baris ini mencetak isi dari tensor_A menggunakan fungsi `print()`. Ini digunakan untuk menampilkan nilai dan bentuk tensor_A dalam format yang lebih mudah dibaca.

```python
# Menampilkan isi dari tensor_B.T
print(tensor_B.T)
```

Baris ini mencetak isi dari tensor_B setelah dilakukan operasi transpose (`tensor_B.T`). Operasi transpose mengubah baris menjadi kolom dan sebaliknya. Jadi, jika tensor_B awalnya memiliki bentuk (3, 2), setelah operasi transpose, bentuknya menjadi (2, 3). Ini digunakan untuk menampilkan nilai dan bentuk tensor_B setelah operasi transpose.

In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


Hasil output yang diberikan adalah nilai-nilai dari tensor_A dan tensor_B setelah operasi transpose (`tensor_B.T`). Berikut penjelasan untuk masing-masing hasil output:

- **`tensor([[1., 2.], [3., 4.], [5., 6.]])`**:
  - Ini adalah isi dari tensor_A. Tensor_A adalah matriks dengan bentuk (3, 2), yang berarti memiliki 3 baris dan 2 kolom. Nilai-nilai matriksnya adalah:
    ```
    1.  2.
    3.  4.
    5.  6.
    ```

- **`tensor([[ 7.,  8.,  9.], [10., 11., 12.]])`**:
  - Ini adalah isi dari tensor_B setelah operasi transpose (`tensor_B.T`). Setelah operasi transpose, tensor_B memiliki bentuk (2, 3), yang berarti memiliki 2 baris dan 3 kolom. Nilai-nilai matriksnya adalah:
    ```
    7.  8.  9.
    10. 11. 12.
    ```

Output ini memperlihatkan nilai-nilai matriks untuk tensor_A dan tensor_B setelah operasi transpose pada tensor_B.

```python
# Menampilkan bentuk (shape) asli dari tensor_A dan tensor_B
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
```

Baris ini mencetak bentuk (shape) asli dari tensor_A dan tensor_B menggunakan f-string. Ini memberikan informasi tentang jumlah baris dan kolom dari masing-masing tensor sebelum operasi perkalian matriks.

```python
# Menampilkan bentuk (shape) baru setelah operasi transpose pada tensor_B
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
```

Baris ini mencetak bentuk (shape) baru dari tensor_A dan tensor_B setelah operasi transpose pada tensor_B. Operasi transpose mengubah jumlah baris menjadi jumlah kolom dan sebaliknya.

```python
# Menampilkan informasi tentang operasi perkalian matriks yang akan dilakukan
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
```

Baris ini memberikan informasi tentang operasi perkalian matriks yang akan dilakukan, dengan menekankan bahwa dimensi dalam tengah dari kedua tensor cocok (jumlah kolom tensor_A sama dengan jumlah baris tensor_B.T), sehingga perkalian matriks dapat dilakukan.

```python
# Menampilkan output dari operasi perkalian matriks
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
```

Baris ini mencetak hasil dari operasi perkalian matriks antara tensor_A dan tensor_B setelah operasi transpose pada tensor_B.

```python
# Menampilkan bentuk (shape) dari output
print(f"\nOutput shape: {output.shape}")
```

Baris ini mencetak bentuk (shape) dari output, yang memberikan informasi tentang jumlah baris dan kolom dari hasil operasi perkalian matriks.

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Hasil output memberikan informasi tentang bentuk (shape) dari tensor_A, tensor_B.T, dan hasil dari operasi perkalian matriks antara tensor_A dan tensor_B.T. Berikut penjelasan untuk masing-masing hasil output:

- **`Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])`**:
  - Ini adalah bentuk asli dari tensor_A dan tensor_B sebelum operasi perkalian matriks. Kedua tensor memiliki bentuk (3, 2), yang berarti masing-masing memiliki 3 baris dan 2 kolom.

- **`New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])`**:
  - Ini adalah bentuk baru dari tensor_B setelah operasi transpose (`tensor_B.T`). Setelah transpose, tensor_B memiliki bentuk (2, 3), yang berarti memiliki 2 baris dan 3 kolom.

- **`Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match`**:
  - Ini memberikan informasi bahwa bentuk tensor_A adalah (3, 2), bentuk tensor_B.T adalah (2, 3), dan operasi perkalian matriks dapat dilakukan karena jumlah kolom tensor_A sama dengan jumlah baris tensor_B.T.

- **`Output:`**:
  - Ini adalah hasil dari operasi perkalian matriks antara tensor_A dan tensor_B.T. Hasilnya adalah matriks dengan bentuk (3, 3), yang berarti memiliki 3 baris dan 3 kolom.

- **`Output shape: torch.Size([3, 3])`**:
  - Ini adalah bentuk (shape) dari hasil operasi perkalian matriks. Hasilnya adalah matriks dengan bentuk (3, 3), yang berarti memiliki 3 baris dan 3 kolom.

You can also use [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) which is a short for `torch.matmul()`.

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Without the transpose, the rules of matrix mulitplication aren't fulfilled and we get an error like above.

How about a visual?

![visual demo of matrix multiplication](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

You can create your own matrix multiplication visuals like this at http://matrixmultiplication.xyz/.

> **Note:** A matrix multiplication like this is also referred to as the [**dot product**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) of two matrices.



Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$

Where:
* `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
* `A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
  * **Note:** You might also often see `W` or another letter like `X` used to showcase the weights matrix.
* `b` is the bias term used to slightly offset the weights and inputs.
* `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

Do you notice anything to do with the shapes?

```python
# Membuat tensor_A yang memiliki seed tertentu agar hasilnya dapat direproduksi
torch.manual_seed(42)
```

Baris ini menggunakan fungsi `torch.manual_seed(42)` untuk menetapkan seed (benih) pada generator angka acak PyTorch. Ini dilakukan untuk membuat hasil dari operasi-operasi acak menjadi dapat direproduksi, artinya hasilnya akan selalu sama jika seed yang sama digunakan.

```python
# Membuat layer linear dengan matrix multiplication
linear = torch.nn.Linear(in_features=2, out_features=6)
```

Baris ini membuat layer linear menggunakan modul `torch.nn.Linear`. Layer ini melakukan operasi matrix multiplication dengan input yang memiliki dua fitur (`in_features=2`) dan menghasilkan output dengan enam fitur (`out_features=6`).

```python
# Membuat input tensor x menggunakan tensor_A
x = tensor_A
```

Baris ini membuat tensor input `x` dengan menggunakan nilai-nilai dari tensor_A.

```python
# Melakukan operasi matrix multiplication menggunakan layer linear
output = linear(x)
```

Baris ini melakukan operasi matrix multiplication antara tensor input `x` dan bobot (weights) dari layer linear. Hasilnya adalah tensor output.

```python
# Menampilkan bentuk (shape) dari input dan output
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")
```

Baris ini mencetak bentuk (shape) dari tensor input (`x`) dan tensor output (`output`) untuk memberikan informasi tentang jumlah baris dan kolom dari keduanya.

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


Output tersebut merupakan hasil dari operasi matriks dengan menggunakan model neural network atau lapisan linier (linear layer) dalam kerangka kerja PyTorch. Dalam hal ini, matriks input memiliki bentuk torch.Size([3, 2]), yang berarti terdapat 3 sampel data, masing-masing dengan 2 fitur.

Output yang diberikan memiliki bentuk torch.Size([3, 6]), yang berarti setiap sampel data sekarang direpresentasikan dalam bentuk vektor dengan 6 elemen. Proses ini umumnya melibatkan perkalian matriks antara matriks bobot (weights) dan matriks input, diikuti dengan penambahan bias (bias addition). Operasi ini dapat direpresentasikan sebagai berikut:

\[ \text{Output} = \text{Input} \times \text{Weights} + \text{Bias} \]

Dalam hal ini, bobot dan bias telah diatur selama pelatihan model neural network. Output yang diberikan adalah hasil dari operasi tersebut, dan nilai-nilai tersebut disertakan dengan grad_fn yang menunjukkan bahwa tensor tersebut adalah hasil dari operasi backward pass yang mungkin telah terjadi selama pelatihan untuk menghitung gradien.

Secara lebih spesifik, matriks input \(\text{torch.Size}([3, 2])\) telah dikalikan dengan matriks bobot yang memiliki bentuk yang sesuai agar dapat menghasilkan matriks output \(\text{torch.Size}([3, 6])\). Output ini mungkin juga telah melewati fungsi aktivasi tertentu tergantung pada arsitektur model neural network yang digunakan.

> **Question:** What happens if you change `in_features` from 2 to 3 above? Does it error? How could you change the shape of the input (`x`) to accomodate to the error? Hint: what did we have to do to `tensor_B` above?

If you've never done it before, matrix multiplication can be a confusing topic at first.

But after you've played around with it a few times and even cracked open a few neural networks, you'll notice it's everywhere.

Remember, matrix multiplication is all you need.

![matrix multiplication is all you need](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*When you start digging into neural network layers and building your own, you'll find matrix multiplications everywhere. **Source:** https://marksaroufim.substack.com/p/working-class-deep-learner*

### Finding the min, max, mean, sum, etc (aggregation)

Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.





In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Now let's perform some aggregation.

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


> **Note:** You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.

You can also do the same as above with `torch` methods.

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max

You can also find the index of a tensor where the max or minimum occurs with [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) and [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the [softmax activation function](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html)).

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Change tensor datatype

As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in `torch.float64` and another is in `torch.float32`, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using [`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) where the `dtype` parameter is the datatype you'd like to use.

First we'll create a tensor and check it's datatype (the default is `torch.float32`).

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

Now we'll create another tensor the same as before but change its datatype to `torch.float16`.



In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

And we can do something similar to make a `torch.int8` tensor.

In [ ]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

> **Note:** Different datatypes can be confusing to begin with. But think of it like this, the lower the number (e.g. 32, 16, 8), the less precise a computer stores the value. And with a lower amount of storage, this generally results in faster computation and a smaller overall model. Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts. For more on this, I'd read up about [precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)).

> **Exercise:** So far we've covered a fair few tensor methods but there's a bunch more in the [`torch.Tensor` documentation](https://pytorch.org/docs/stable/tensors.html), I'd recommend spending 10-minutes scrolling through and looking into any that catch your eye. Click on them and then write them out in code yourself to see what happens.

### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

First, we'll create a tensor.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Now let's add an extra dimension with `torch.reshape()`.

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

We can also change the view with `torch.view()`.

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Remember though, changing the view of a tensor with `torch.view()` really only creates a new view of the *same* tensor.

So changing the view changes the original tensor too.

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()` (I remember this as *squeezing* the tensor to only have dimensions over 1).

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


You can also rearrange the order of axes values with `torch.permute(input, dims)`, where the `input` gets turned into a *view* with new `dims`.

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


> **Note**: Because permuting returns a *view* (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


You can also use `:` to specify "all values in this dimension" and then use a comma (`,`) to add another dimension.

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Indexing can be quite confusing to begin with, especially with larger tensors (I still have to try indexing multiple times to get it right). But with a bit of practice and following the data explorer's motto (***visualize, visualize, visualize***), you'll start to get the hang of it.

## PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

Let's try them out.

Berikut adalah penjelasan baris per baris dari kode yang diberikan:

1. `import torch`: Mengimpor modul PyTorch yang menyediakan fungsionalitas untuk komputasi tensor dan membangun model neural network.

2. `import numpy as np`: Mengimpor modul NumPy dengan alias `np`. NumPy digunakan untuk manipulasi array dan operasi matematika.

3. `array = np.arange(1.0, 8.0)`: Membuat array NumPy dengan menggunakan fungsi `arange` yang menghasilkan array dengan rentang nilai dari 1.0 hingga 7.0 (nilai akhir tidak termasuk). Sebagai contoh, `array` dapat berisi nilai `[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]`.

4. `tensor = torch.from_numpy(array)`: Mengonversi array NumPy menjadi tensor PyTorch menggunakan fungsi `torch.from_numpy()`. Proses ini membuat tensor PyTorch yang berbagi memori dengan array NumPy, sehingga perubahan pada salah satu dari keduanya akan tercermin pada yang lain.

5. `array, tensor`: Mencetak nilai dari variabel `array` dan `tensor`. Ini digunakan untuk menunjukkan perbedaan representasi antara array NumPy dan tensor PyTorch yang sesuai, serta bagaimana keduanya dapat berkaitan melalui konversi.

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Output tersebut menunjukkan nilai dari array NumPy dan tensor PyTorch yang telah dibuat. Berikut adalah penjelasan hasil outputnya:

1. `array([1., 2., 3., 4., 5., 6., 7.])`: Ini adalah representasi dari array NumPy yang telah dibuat menggunakan `np.arange(1.0, 8.0)`. Array ini berisi nilai dari 1.0 hingga 7.0 dengan tipe data float.

2. `tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)`: Ini adalah representasi dari tensor PyTorch yang telah dihasilkan dari array NumPy. Tensor ini memiliki nilai yang sama dengan array NumPy dan tipe data float64 (double precision). Saat konversi dari NumPy array ke tensor PyTorch, tipe data float NumPy diubah menjadi float64 dalam tensor PyTorch.

Perlu diingat bahwa tensor PyTorch dan array NumPy dapat berbagi memori, sehingga perubahan pada satu objek dapat tercermin pada objek lainnya. Namun, ada perbedaan dalam fungsionalitas dan propertinya, seperti dukungan operasi GPU, fungsionalitas autograd PyTorch pada tensor, dan sebagainya.

> **Note:** By default, NumPy arrays are created with the datatype `float64` and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).
>
> However, many PyTorch calculations default to using `float32`.
>
> So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use `tensor = torch.from_numpy(array).type(torch.float32)`.

Because we reassigned `tensor` above, if you change the tensor, the array stays the same.

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

And if you want to go from PyTorch tensor to NumPy array, you can call `tensor.numpy()`.

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

And the same rule applies as above, if you change the original `tensor`, the new `numpy_tensor` stays the same.

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

``start with random numbers -> tensor operations -> try to make better (again and again and again)``

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

Berikut adalah penjelasan baris per baris dari kode yang diberikan:

1. `import torch`: Mengimpor modul PyTorch yang menyediakan fungsionalitas untuk komputasi tensor dan membangun model neural network.

2. `random_tensor_A = torch.rand(3, 4)`: Membuat tensor acak \(3 \times 4\) menggunakan fungsi `torch.rand()`. Tensor ini akan berisi nilai acak antara 0 (inklusif) dan 1 (eksklusif).

3. `random_tensor_B = torch.rand(3, 4)`: Membuat tensor acak kedua dengan ukuran \(3 \times 4\) menggunakan fungsi `torch.rand()`.

4. `print(f"Tensor A:\n{random_tensor_A}\n")`: Mencetak tensor A ke layar. Ini adalah cara untuk menampilkan nilai tensor A dalam bentuk yang lebih ramah pengguna. Tanda `\n` digunakan untuk membuat baris baru setelah mencetak tensor A.

5. `print(f"Tensor B:\n{random_tensor_B}\n")`: Mencetak tensor B ke layar dengan format yang serupa.

6. `print(f"Does Tensor A equal Tensor B? (anywhere)")`: Mencetak teks yang bertanya apakah Tensor A sama dengan Tensor B di mana saja. Perhatikan bahwa ini hanya mencetak pertanyaan, bukan hasil perbandingan.

7. `random_tensor_A == random_tensor_B`: Baris ini secara efektif melakukan perbandingan elemen-wise antara kedua tensor. Ini menghasilkan tensor boolean yang memiliki dimensi yang sama seperti tensor asli, dan setiap elemennya menunjukkan apakah nilai yang sesuai dalam tensor A sama dengan nilai yang sesuai dalam tensor B. Namun, dalam kode ini, hasil perbandingan ini tidak ditangkap atau dicetak, sehingga tidak akan muncul di luar hasil dari sel yang sedang dijalankan.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Output ini menunjukkan hasil dari perbandingan elemen-wise antara dua tensor, yaitu Tensor A dan Tensor B. Berikut adalah penjelasan hasil outputnya:

1. **Tensor A**:
   ```
   tensor([[0.8016, 0.3649, 0.6286, 0.9663],
           [0.7687, 0.4566, 0.5745, 0.9200],
           [0.3230, 0.8613, 0.0919, 0.3102]])
   ```

2. **Tensor B**:
   ```
   tensor([[0.9536, 0.6002, 0.0351, 0.6826],
           [0.3743, 0.5220, 0.1336, 0.9666],
           [0.9754, 0.8474, 0.8988, 0.1105]])
   ```

3. **Hasil Perbandingan**:
   ```
   tensor([[False, False, False, False],
           [False, False, False, False],
           [False, False, False, False]])
   ```

   Setiap elemen dalam hasil tensor adalah nilai boolean yang menunjukkan apakah nilai yang sesuai dalam Tensor A sama dengan nilai yang sesuai dalam Tensor B. Dalam hal ini, hasilnya adalah `False` di semua posisi, yang berarti tidak ada elemen yang sama antara Tensor A dan Tensor B.

Dengan kata lain, tidak ada nilai yang sama di antara elemen-elemen Tensor A dan Tensor B.

Just as you might've expected, the tensors come out with different values.

But what if you wanted to created two random tensors with the *same* values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) comes in, where `seed` is an integer (like `42` but it could be anything) that flavours the randomness.

Let's try it out by creating some more *flavoured* random tensors.

Berikut adalah penjelasan baris per baris dari kode yang diberikan:

1. `import torch`: Mengimpor modul PyTorch yang menyediakan fungsionalitas untuk komputasi tensor dan membangun model neural network.

2. `import random`: Mengimpor modul Python `random`, yang digunakan untuk mengatur seed dalam pengaturan generator angka acak.

3. `RANDOM_SEED=42`: Mendefinisikan nilai seed yang akan digunakan untuk menghasilkan angka acak. Seed ini digunakan untuk memastikan bahwa penghasilan angka acak dapat direproduksi.

4. `torch.manual_seed(seed=RANDOM_SEED)`: Mengatur seed untuk generator angka acak PyTorch menggunakan fungsi `torch.manual_seed()`. Ini memastikan bahwa angka acak yang dihasilkan oleh PyTorch akan konsisten ketika seed tetap sama.

5. `random_tensor_C = torch.rand(3, 4)`: Membuat tensor acak \(3 \times 4\) menggunakan fungsi `torch.rand()`. Seed PyTorch yang telah diatur sebelumnya memastikan bahwa tensor ini akan menghasilkan nilai yang sama setiap kali kode dijalankan dengan seed yang sama.

6. `torch.random.manual_seed(seed=RANDOM_SEED)`: Mengatur seed untuk generator angka acak PyTorch secara manual. Ini perlu dilakukan setiap kali ingin menggunakan fungsi random yang ada dalam modul PyTorch, seperti `torch.rand()`, untuk memastikan konsistensi hasil.

7. `random_tensor_D = torch.rand(3, 4)`: Membuat tensor acak kedua \(3 \times 4\) menggunakan fungsi `torch.rand()`. Karena seed telah diatur dengan `torch.random.manual_seed()`, tensor ini akan menghasilkan nilai yang sama dengan `random_tensor_C` karena seed yang digunakan sama.

8. `print(f"Tensor C:\n{random_tensor_C}\n")`: Mencetak tensor C ke layar.

9. `print(f"Tensor D:\n{random_tensor_D}\n")`: Mencetak tensor D ke layar.

10. `print(f"Does Tensor C equal Tensor D? (anywhere)")`: Mencetak teks yang bertanya apakah Tensor C sama dengan Tensor D di mana saja. Perhatikan bahwa ini hanya mencetak pertanyaan, bukan hasil perbandingan.

11. `random_tensor_C == random_tensor_D`: Baris ini secara efektif melakukan perbandingan elemen-wise antara kedua tensor. Ini menghasilkan tensor boolean yang memiliki dimensi yang sama seperti tensor asli, dan setiap elemennya menunjukkan apakah nilai yang sesuai dalam tensor C sama dengan nilai yang sesuai dalam tensor D. Namun, hasil perbandingan ini tidak ditangkap atau dicetak, sehingga tidak akan muncul di luar hasil dari sel yang sedang dijalankan.

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Output ini menunjukkan hasil dari perbandingan elemen-wise antara dua tensor, yaitu Tensor C dan Tensor D. Berikut adalah penjelasan hasil outputnya:

1. **Tensor C**:
   ```
   tensor([[0.8823, 0.9150, 0.3829, 0.9593],
           [0.3904, 0.6009, 0.2566, 0.7936],
           [0.9408, 0.1332, 0.9346, 0.5936]])
   ```

2. **Tensor D**:
   ```
   tensor([[0.8823, 0.9150, 0.3829, 0.9593],
           [0.3904, 0.6009, 0.2566, 0.7936],
           [0.9408, 0.1332, 0.9346, 0.5936]])
   ```

3. **Hasil Perbandingan**:
   ```
   tensor([[True, True, True, True],
           [True, True, True, True],
           [True, True, True, True]])
   ```

   Setiap elemen dalam hasil tensor adalah nilai boolean yang menunjukkan apakah nilai yang sesuai dalam Tensor C sama dengan nilai yang sesuai dalam Tensor D. Dalam hal ini, hasilnya adalah `True` di semua posisi, yang berarti setiap elemen pada Tensor C sama dengan elemen yang sesuai pada Tensor D.

Dengan kata lain, Tensor C dan Tensor D identik, dan tidak ada perbedaan antara elemen-elemen mereka. Hal ini sesuai dengan ekspektasi karena kedua tensor tersebut dibuat dengan seed yang sama, sehingga keduanya menghasilkan urutan angka acak yang identik.

Nice!

It looks like setting the seed worked.

> **Resource:** What we've just covered only scratches the surface of reproducibility in PyTorch. For more, on reproducbility in general and random seeds, I'd checkout:
> * [The PyTorch reproducibility documentation](https://pytorch.org/docs/stable/notes/randomness.html) (a good exericse would be to read through this for 10-minutes and even if you don't understand it now, being aware of it is important).
> * [The Wikipedia random seed page](https://en.wikipedia.org/wiki/Random_seed) (this'll give a good overview of random seeds and pseudorandomness in general).

## Running tensors on GPUs (and making faster computations)

Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

> **Note:** When I reference "GPU" throughout this course, I'm referencing a [Nvidia GPU with CUDA](https://developer.nvidia.com/cuda-gpus) enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.




### 1. Getting a GPU

You may already know what's going on when I say GPU. But if not, there are a few ways to get access to one.

| **Method** | **Difficulty to setup** | **Pros** | **Cons** | **How to setup** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Easy | Free to use, almost zero setup required, can share work with others as easy as a link | Doesn't save your data outputs, limited compute, subject to timeouts | [Follow the Google Colab Guide](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Use your own | Medium | Run everything locally on your own machine | GPUs aren't free, require upfront cost | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/locally/) |
| Cloud computing (AWS, GCP, Azure) | Medium-Hard | Small upfront cost, access to almost infinite compute | Can get expensive if running continually, takes some time to setup right | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/cloud-partners/) |

There are more options for using GPUs but the above three will suffice for now.

Personally, I use a combination of Google Colab and my own personal computer for small scale experiments (and creating this course) and go to cloud resources when I need more compute power.

> **Resource:** If you're looking to purchase a GPU of your own but not sure what to get, [Tim Dettmers has an excellent guide](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means "run this on the command line".



In [ ]:
!nvidia-smi

Sat Jan 21 08:34:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    On   | 00000000:01:00.0 Off |                  N/A |
| 40%   30C    P8     7W / 280W |    177MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If you don't have a Nvidia GPU accessible, the above will output something like:

```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

In that case, go back up and follow the install steps.

If you do have a GPU, the line above will output something like:

```
Wed Jan 19 22:09:08 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```



### 2. Getting PyTorch to run on the GPU

Once you've got a GPU ready to access, the next step is getting PyTorch to use for storing data (tensors) and computing on data (performing operations on tensors).

To do so, you can use the [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html) package.

Rather than talk about it, let's try it out.

You can test if PyTorch has access to a GPU using [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available).


In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

If the above outputs `True`, PyTorch can see and use the GPU, if it outputs `False`, it can't see the GPU and in that case, you'll have to go back through the installation steps.

Now, let's say you wanted to setup your code so it ran on CPU *or* the GPU if it was available.

That way, if you or someone decides to run your code, it'll work regardless of the computing device they're using.

Let's create a `device` variable to store what kind of device is available.

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

If the above output `"cuda"` it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output `"cpu"`, our PyTorch code will stick with the CPU.

> **Note:** In PyTorch, it's best practice to write [**device agnostic code**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). This means code that'll run on CPU (always available) or GPU (if available).

If you want to do faster computing you can use a GPU but if you want to do *much* faster computing, you can use multiple GPUs.

You can count the number of GPUs PyTorch has access to using [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count).

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across *all* GPUs).

### 3. Putting tensors (and models) on the GPU

You can put tensors (and models, we'll see this later) on a specific device by calling [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) on them. Where `device` is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our **device agnostic code** (see above), it'll run on the CPU.

> **Note:** Putting a tensor on GPU using `to(device)` (e.g. `some_tensor.to(device)`) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:
>
> `some_tensor = some_tensor.to(device)`

Let's try creating a tensor and putting it on the GPU (if it's available).

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

If you have a GPU available, the above code will output something like:

```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
```

Notice the second tensor has `device='cuda:0'`, this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be `'cuda:0'` and `'cuda:1'` respectively, up to `'cuda:n'`).



### 4. Moving tensors back to the CPU

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

Let's try using the [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) method on our `tensor_on_gpu`.

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Instead, to get a tensor back to CPU and usable with NumPy we can use [`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html).

This copies the tensor to CPU memory so it's usable with CPUs.

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises

All of the exercises are focused on practicing the code above.

You should be able to complete them by referencing each section or by following the resource(s) linked.

**Resources:**

* [Exercise template notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb).
* [Example solutions notebook for 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb) (try the exercises *before* looking at this).

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).
2. Create a random tensor with shape `(7, 7)`.
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).
4. Set the random seed to `0` and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.
6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

## Extra-curriculum

* Spend 1-hour going through the [PyTorch basics tutorial](https://pytorch.org/tutorials/beginner/basics/intro.html) (I'd recommend the [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) and [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html) sections).
* To learn more on how a tensor can represent data, see this video: [What's a tensor?](https://youtu.be/f5liqUk0ZTw)